version: '2'
services:
  app:
    build: .
    ports:
     - 4000:8080
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend


volumes:
  mongo-data:

networks:
  backend:
